version: '3'
services:
  backend:
    build: ./backend/
    command: node index.js
    volumes:
      - ./backend/:/usr/src/app/
  frontend:
    build: ./frontend/
    command: npm run dev
    volumes:
      - ./frontend/:/usr/src/app/
  nginx:
    image: nginx:latest
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
